server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  destination:
    folder: src/main/resources/static/

application:
  security:
    jwt:
      secret_key: ${SECRET_KEY}
      expiration: 8640000
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:*}

aws:
  s3:
    key: ${AWS_KEY}
    secret: ${AWS_SECRET}
    region: us-east-2
    bucket: ${BUCKET_NAME}

logging:
  level:
    software:
      amazon:
        awssdk: DEBUG